const articles = [
    {
      id: 'https://www.cnbc.com/2025/08/02/how-florida-quietly-surpassed-california-in-solar-growth.html',
      title: 'How Florida quietly surpassed California in solar growth',
      description: 'Florida added more solar than California in 2024, despite no climate mandate. Can the boom last? CNBC visited Babcock Ranch to find out.',
      url: 'https://www.cnbc.com/2025/08/02/how-florida-quietly-surpassed-california-in-solar-growth.html',
      image: 'https://sc.cnbcfm.com/applications/cnbc.com/staticcontent/img/cnbc_logo_new.png?v=1524171804&w=1920&h=1080',
      publishedAt: '2025-08-02T16:00:01Z',
      source: { id: null, name: 'CNBC' },
      content: `Solar energy is booming across the U.S. and, for the first time, Florida is catching up to industry powerhouses Texas and California.Despite removing climate change from its official state policy in 2024, Florida added more utility-scale solar than California last year, with over 3 gigawatts of new capacity coming online. "This is not a fluke," said Sylvia Leyva Martinez, senior analyst at Wood Mackenzie. "Florida is now shaping national solar growth."The surge is being driven by utilities, not rooftop panels. Florida Power & Light alone built over 70% of the state's new solar last year. A state rule lets developers skip lengthy siting reviews for projects under 75 megawatts, which speeds up construction and cuts costs."There's no silver bullet," said Syd Kitson, founder of Babcock Ranch, a town designed to be powered almost entirely by solar. "But one thing Florida got right is acceptance. Here, people want solar. And we're proving it works."Babcock Ranch runs on its own microgrid and stayed online during Hurricane Ian in 2022, while much of southwest Florida went dark."We didn't lose power, internet, or water," said Don Bishop, a homeowner there. "That changes how you think about energy."The economics are doing the rest. With industrial demand rising and natural gas prices climbing, solar is increasingly the cheapest option, even without subsidies."Utilities aren't building solar because it's green," Martinez said. "They're doing it because it's cheaper."But new challenges are emerging.In July, President Trump signed the One Big Beautiful Bill, which accelerates the rollback of solar and wind tax credits. Homeowners lose the federal investment credit after 2025. Developers face tighter deadlines and stricter sourcing rules."It won't kill the market," said Zoë Gaston, an analyst who follows the solar industry at Wood Mackenzie. "But it makes the math harder."Analysts now expect a 42% drop in rooftop solar installs in Florida over the next five years. And while util`
    },
    {
      id: 'https://www.businessinsider.com/att-ceo-john-stankey-email-employee-feedback-survey-rto-policy-2025-8',
      title: "Read AT&T CEO's Frank Response to Employee Survey After RTO Mandate",
      description: 'AT&T CEO John Stankey issued a lengthy memo addressing the shift to a "more market-based culture" and the results of an employee engagement survey.',
      url: 'https://www.businessinsider.com/att-ceo-john-stankey-email-employee-feedback-survey-rto-policy-2025-8',
      image: 'https://i.insider.com/688d76a385e81483682f2fe4?width=1200&format=jpeg',
      publishedAt: '2025-08-02T13:12:00Z',
      source: { id: null, name: 'Business Insider' },
      content: '<img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know <img class="no-script" src="/public/assets/logos/placeholder.png" /> Business Insider tells the innovative stories you want to know'
    },
    {
      id: 'https://www.yahoo.com/news/articles/wanna-king-democrats-fume-trump-130503313.html',
      title: '‘Wanna-be king’: Democrats fume at Trump move to oust BLS head',
      description: 'Criticism is mounting after President Trump moved to oust the head of the Bureau of Labor Statistics (BLS) on Friday following a dismal jobs report. Trump accused BLS commissioner Erika McEntarfer, an appointee of former President Biden, of skewing job numbers in the latest report, which showed the U.S. adding only 73,000 jobs last month…',
      url: 'https://www.yahoo.com/news/articles/wanna-king-democrats-fume-trump-130503313.html',
      image: 'https://media.zenfs.com/en/the_hill_articles_341/7dd3bb0bccd550e18c6cff9e9bd8f40d',
      publishedAt: '2025-08-02T13:05:03Z',
      source: { id: null, name: 'Yahoo Home' },
      content: 'Criticism is mounting after President Trump moved to oust the head of the Bureau of Labor Statistics (BLS) on Friday following a dismal jobs report.Trump accused BLS commissioner Erika McEntarfer, an appointee of former President Biden, of skewing job numbers in the latest report, which showed the U.S. adding only 73,000 jobs last month and the unemployment rate increasing slightly.Revisions in the report also showed that the U.S. added 258,000 fewer jobs in May and June than the Labor Department first reported, according to BLS data.AdvertisementAdvertisementAdvertisementAdvertisement“In my opinion, today’s Jobs Numbers were RIGGED in order to make the Republicans, and ME, look bad,” he wrote on Truth Social. Later, he called for McEntarfer’s ouster, which sparked some backlash on Capitol Hill.“Instead of helping people get good jobs, Donald Trump just fired the statistician who reported bad jobs data that the wanna-be king doesn’t like,” Sen. Elizabeth Warren (D-Mass.) posted on social platform X.The gloomy jobs report raised serious questions about the strength of the U.S. economy, especially in light of Trump’s sweeping tariffs, which have caused anxieties in the global market.Sen. Lisa Blunt Rochester (D-Del.) called the president’s response “deeply irresponsible.”AdvertisementAdvertisementAdvertisementAdvertisement“Firing the head of the Bureau of Labor Statistics because they accurately report on your struggling economy isn’t just corrupt, it’s deeply irresponsible,” she wrote online. “Undermining our economic data is only going to create further chaos and uncertainty for our businesses big and small.”Senate Minority Leader Chuck Schumer (D-N.Y.) also turned the tables back on Trump in a semi-mocking post on X.“BREAKING: I did some research into Trump’s Deep State and found this photo of the real government employee responsible for the job loss numbers,” Schumer wrote Friday, sharing a photo of the president himself. “Trump must fire him immediately.”Rep. Pra'
    }
  ]

  export default articles;